import type { GameDictionary } from './types';

export const gameEn: GameDictionary = {
  meta: {
    title: 'Career Quest — Play Philip Scheer’s 20-Year Journey in Tech',
    description:
      'A playable resume: walk through 20+ years of technology leadership, unlock development, management and business skills, and beat real-world bosses — from the first Hello World to 1M+ concurrent users.',
  },
  page: {
    title: 'Career Quest',
    intro:
      'Meet me by playing. Walk forward (and back) through 20+ years in technology: collect skills, earn badges and beat the real challenges I faced — the final boss is one million concurrent users.',
    noscript:
      'Career Quest needs JavaScript. Prefer the classic route? Check the Experience page or download the resume.',
  },
  ui: {
    startTitle: 'CAREER QUEST',
    tagline: '20+ years turning ideas into low-cost, high-performance products. Play the journey.',
    howTitle: 'How to play',
    how: [
      '← → or A/D — walk through time, forward and back',
      'Space or ↑ — jump',
      'E or tap the banner — face the boss',
      'Walk into the floating gems to collect skills (Development · Management · Business)',
      'Beat each era’s boss to unlock the next chapter',
    ],
    recruiterNote:
      'Recruiter in a hurry? Open the timeline map: fast-travel to any phase — each one is a mini-CV.',
    startBtn: 'Press Start (2005)',
    openMapBtn: 'Open timeline map',
    hudXp: 'XP',
    hudSkills: 'Skills',
    hudMap: 'Map',
    hudCv: 'Mini-CV',
    bossPrompt: 'Press E · Face',
    skillUnlocked: 'Skill unlocked',
    badgeEarned: 'Badge earned',
    bossChallenge: 'Boss challenge',
    wrongTitle: 'Not this time',
    tryAgain: 'Try again',
    victoryTitle: 'Challenge cleared',
    continueBtn: 'Continue',
    closeBtn: 'Close',
    mapTitle: 'Career timeline',
    mapHint: 'Click a phase to travel there. This map is the whole resume at a glance.',
    travelBtn: 'Travel',
    cvTitle: 'Mini-CV',
    trees: { dev: 'Development', mgmt: 'Management', biz: 'Business' },
    touchLeft: 'Walk left',
    touchRight: 'Walk right',
    touchJump: 'Jump',
    touchAction: 'Interact',
  },
  final: {
    title: 'Next level: your company?',
    body:
      'You just walked through 20+ years — from a technical school classroom to a real-time platform serving 1M+ concurrent users at 57% lower cost. The skills are real, the metrics are real, and the next boss fight could be yours.',
    statsXp: 'XP earned',
    statsSkills: 'Skills collected',
    statsBadges: 'Badges earned',
    ctaContact: 'Contact me',
    ctaResume: 'Download resume',
    ctaLinkedin: 'Connect on LinkedIn',
    replay: 'Play again',
  },
  zones: [
    {
      id: 'school',
      year: '2005–2007',
      company: 'Clovis Bevilacqua',
      role: 'IT Technician (Technical School)',
      miniCv: [
        'Technical degree in Information Technology.',
        'First contact with programming logic and object-oriented programming.',
        'Where the whole journey starts — tutorial level.',
      ],
      skills: [
        { id: 'logic', name: 'Programming Logic', tree: 'dev', evidence: 'Technical school in IT — Clovis Bevilacqua (2005–2007).' },
        { id: 'oop', name: 'OOP Foundations', tree: 'dev', evidence: 'Object-oriented programming, the base of everything that follows.' },
      ],
      boss: {
        name: 'THE FINAL EXAM',
        intro: 'A wall of questions blocks the door to the real world. Memorizers do not pass.',
        question: 'The exam shows a loop you have never seen. What gets you through?',
        options: [
          'Memorize the answer key',
          'Trace the logic step by step',
          'Copy from a friend and hope',
        ],
        correct: 1,
        hint: 'In tech, understanding beats memorizing — every single time.',
        result: 'Logic first. Technical degree earned — next stop: production code.',
      },
    },
    {
      id: 'datatex',
      year: '2008–2009',
      company: 'Datatex',
      role: 'Web Developer',
      miniCv: [
        'First developer job: WordPress, PHP, HTML/CSS/JS and Python/Django projects at different stages.',
        'Fixing live problems on existing client projects.',
        'Started B.Sc. in Computer Science at FAENAC (2008–2011) in parallel.',
      ],
      skills: [
        { id: 'web', name: 'PHP & WordPress', tree: 'dev', evidence: 'Handled client sites and custom WordPress plugins at Datatex.' },
        { id: 'django', name: 'Python / Django', tree: 'dev', evidence: 'Projects in Python-Django alongside PHP and JS work.' },
      ],
      boss: {
        name: 'THE SITE DOWN IN PRODUCTION',
        intro: 'A client’s site just broke. Real users, real business, no staging environment.',
        question: 'The site is down and the fix must go live now. First move?',
        options: [
          'Reproduce the bug and read the error logs',
          'Rewrite the whole site from scratch',
          'Blame the previous developer',
        ],
        correct: 0,
        hint: 'You cannot fix what you cannot reproduce.',
        result: 'First production fix shipped. WordPress, PHP or Django — whatever the project needs.',
      },
    },
    {
      id: 'brpart',
      year: '2009–2012',
      company: 'BR part / Synchro',
      role: 'Systems Analyst',
      miniCv: [
        'Third-level support, installation and tuning of app servers (JBoss, WebSphere).',
        'Java web applications, project documentation and problem-solving procedures.',
        'Training and presentation of Brazilian fiscal tools (NFe / CTe / EMIF).',
      ],
      skills: [
        { id: 'javaee', name: 'Java EE', tree: 'dev', evidence: 'Java applications configured, customized and deployed on JBoss/WebSphere.' },
        { id: 'n3', name: 'N3 Support', tree: 'mgmt', evidence: 'Third-level support: the user’s pain becomes your roadmap.' },
        { id: 'fiscal', name: 'Fiscal Compliance BR', tree: 'biz', evidence: 'NFe, CTe and EMIF — deep Brazilian tax and fiscal requirements.' },
      ],
      boss: {
        name: 'THE COMPLIANCE MONSTER',
        intro: 'It attacks with a new NFe layout every few months. Every client must stay compliant.',
        question: 'A new NFe layout drops next month. How do you survive Brazilian fiscal rules?',
        options: [
          'Hardcode the new layout as fast as possible',
          'Read the spec, version the layouts, document the change',
          'Wait — maybe the government postpones it',
        ],
        correct: 1,
        hint: 'Compliance is a moving target. Versioning and documentation are your armor.',
        result: 'NFe/CTe tamed. Documentation and support discipline became permanent skills.',
      },
      badge: {
        id: 'graduation',
        icon: '🎓',
        name: 'Graduation',
        desc: 'B.Sc. in Computer Science — FAENAC University, São Paulo (2008–2011).',
      },
    },
    {
      id: 'itc',
      year: '2012–2015',
      company: 'IT Convergence',
      role: 'IT Consultant',
      miniCv: [
        'International consultancy: support up to third level for global clients.',
        'Installation and updates of application servers (JBoss, WebSphere, OA).',
        'Documentation, project plans and problem-solving procedures — in English.',
      ],
      skills: [
        { id: 'appservers', name: 'App Servers at Scale', tree: 'dev', evidence: 'JBoss, WebSphere and OA installed, updated and kept alive for enterprise clients.' },
        { id: 'english', name: 'Professional English', tree: 'biz', evidence: 'Daily contact with international partners and customers.' },
      ],
      boss: {
        name: 'THE 3 AM SERVER DOWN',
        intro: 'Production is down, the clock says 3:07 AM, and the customer on the call speaks only English.',
        question: 'What now?',
        options: [
          'Wait for the morning shift',
          'Join the call, communicate status clearly, restore service, write the postmortem',
          'Restart everything and say nothing',
        ],
        correct: 1,
        hint: 'Incidents are won with communication + procedure, not silence.',
        result: 'Incident closed. International clients, English under pressure, procedures documented.',
      },
      badge: {
        id: 'english',
        icon: '🌐',
        name: 'English Unlocked',
        desc: 'Full professional English — the key that opened the international market.',
      },
    },
    {
      id: 'synchro',
      year: '2015–2017',
      company: 'Synchro',
      role: 'Senior J2EE Developer',
      miniCv: [
        'Integrations with Oracle E-Business Suite (AR/RI) and Oracle Retail using ODI and BPEL.',
        'Integrations with SAP Business One; PL/SQL, Java EE, VB6, ABAP and HANA.',
        'Deep expertise in Brazilian fiscal requirements across the whole tax solution suite.',
      ],
      skills: [
        { id: 'oracle', name: 'Oracle PL/SQL & HANA', tree: 'dev', evidence: 'PL/SQL, ODI, BPEL and HANA across enterprise fiscal systems.' },
        { id: 'erp', name: 'ERP Integrations', tree: 'dev', evidence: 'Oracle EBS and SAP B1 talking to each other without breaking month-end closing.' },
      ],
      boss: {
        name: 'THE TWO GIANTS',
        intro: 'Oracle EBS on one side. SAP on the other. Data must flow both ways — closing cannot break.',
        question: 'How do you make two ERP giants cooperate?',
        options: [
          'Point-to-point scripts everywhere',
          'An integration layer (ODI/BPEL) with contracts, versioning and monitoring',
          'Weekly manual spreadsheets',
        ],
        correct: 1,
        hint: 'Giants need diplomats: contracts and a proper integration layer.',
        result: 'Senior-level integrations delivered: Oracle ⇄ SAP with ODI, BPEL, PL/SQL and HANA.',
      },
    },
    {
      id: 'didi',
      year: '2017–2019',
      company: '99 (a DiDi company)',
      role: 'Principal Software Engineer — Payments & Architecture',
      miniCv: [
        'Authored the Global Application Architecture across Brazil, USA and China.',
        'SAP B1 ERP integrations (B1if, DI API, Add-ons) for global markets.',
        'Oversaw 18 concurrent projects and third-party contracts; deep fiscal compliance.',
      ],
      skills: [
        { id: 'globalarch', name: 'Global Architecture', tree: 'dev', evidence: 'Author of the Global Application Architecture at 99 (DiDi).' },
        { id: 'payments', name: 'Payments & Fintech', tree: 'biz', evidence: 'Payments domain plus Brazilian fiscal/tax compliance at scale.' },
        { id: 'portfolio', name: 'Portfolio Management', tree: 'mgmt', evidence: '18 concurrent projects delivered on time with third-party contracts.' },
      ],
      boss: {
        name: 'THE 18-PROJECT HYDRA',
        intro: 'Eighteen heads, three countries, one deadline each. Cut one wrong and two grow back.',
        question: '18 concurrent projects across Brazil, USA and China. How do you keep the heads down?',
        options: [
          'Do everything yourself, sleep later',
          'Prioritize by impact, standardize the architecture, delegate and track',
          'Freeze all projects until further notice',
        ],
        correct: 1,
        hint: 'A Principal Engineer scales through architecture and priorities, not hours.',
        result: '18 projects delivered on time — financial-closure data never missed a deadline.',
      },
      badge: {
        id: 'globetrotter',
        icon: '✈️',
        name: 'Globetrotter',
        desc: 'Work travel: New York, California — Palo Alto / Silicon Valley — and Beijing, plus São Paulo, Rio, Belo Horizonte, Curitiba, Campinas, Cuiabá and Maringá across Brazil.',
      },
    },
    {
      id: 'restoque',
      year: '2019–2020',
      company: 'Restoque S/A',
      role: 'Technology & Innovation Manager',
      miniCv: [
        'Led 3 teams — Product, Innovation and UX Labs — 27 people in total.',
        'Product vision and roadmaps from market, competitor and customer research.',
        'Design Sprints, Flutter app redesign, CI/CD (Rancher, Azure, GCP) and a SaaS for high-demand apps.',
      ],
      skills: [
        { id: 'leadership', name: 'Team Leadership', tree: 'mgmt', evidence: '3 teams, 27 people: the switch from writing code to growing people.' },
        { id: 'roadmap', name: 'Roadmaps & Design Sprints', tree: 'mgmt', evidence: 'Product vision built from research, shipped through Scrum cadences.' },
        { id: 'flutter', name: 'Flutter & CI/CD', tree: 'dev', evidence: 'App redesign in Flutter with CI/CD on Rancher, Azure and GCP.' },
      ],
      boss: {
        name: 'THE HAT SWAP',
        intro: 'A critical bug appears. The old you would code all night. But 27 people are watching what you do next.',
        question: 'You are the manager now. What does the leader do?',
        options: [
          'Code it alone overnight — old habits',
          'Put the right people on it, unblock them, protect the roadmap',
          'Escalate straight to the CEO',
        ],
        correct: 1,
        hint: 'The hardest skill for a great engineer: winning through the team.',
        result: 'First leadership chapter: 3 teams, 27 people, roadmaps and a culture of shipping.',
      },
      badge: {
        id: 'firstlead',
        icon: '👑',
        name: 'First Leadership',
        desc: 'From senior engineer to leader of 27 people across Product, Innovation and UX Labs.',
      },
    },
    {
      id: 'dell',
      year: '2020–2022',
      company: 'Dell Technologies',
      role: 'Design System Manager (Remote, USA & Brazil)',
      miniCv: [
        'Built and governed an enterprise design system: standards, documentation, tooling.',
        'Vision and roadmap from market trends, partnering with design and engineering leaders.',
        'Incremental, agile delivery of components — fully remote across US/Brazil teams.',
      ],
      skills: [
        { id: 'designsystem', name: 'Design Systems', tree: 'dev', evidence: 'Enterprise design system governed at Dell Technologies.' },
        { id: 'governance', name: 'Governance', tree: 'mgmt', evidence: 'Standards, documentation and tooling that scale beyond any single team.' },
        { id: 'remote', name: 'Remote International Work', tree: 'mgmt', evidence: '100% remote across US/Brazil teams and time zones.' },
      ],
      boss: {
        name: 'THE INCONSISTENCY CHAOS',
        intro: 'The same button ships with 12 different looks across products. Users notice. Brand suffers.',
        question: 'How do you defeat chaos at enterprise scale?',
        options: [
          'Let each team keep its own style',
          'A governed design system: standards, docs, tooling, incremental adoption',
          'One big-bang redesign — freeze all product work',
        ],
        correct: 1,
        hint: 'Consistency is a system, not a heroic redesign.',
        result: 'Enterprise design system delivered: faster reuse, lower build cost, one brand.',
      },
      badge: {
        id: 'remotemaster',
        icon: '🏠',
        name: 'Remote Master',
        desc: 'Two years leading fully remote across USA/Brazil — before it was normal.',
      },
    },
    {
      id: 'dexco',
      year: '2022–2024',
      company: 'Dexco (Duratex) · Vivadecora',
      role: 'Senior Technology Manager',
      miniCv: [
        'Led the digital technology strategy end to end, systems and IT infrastructure.',
        'Managed 80+ people across squads, running Dexco and Vivadecora in parallel.',
        '50% reduction in database query time through advanced optimization.',
        'AI chatbot for Sales and HR (Python, NLP) integrated with Microsoft Teams.',
      ],
      skills: [
        { id: 'squads', name: 'Squad Scale (80+)', tree: 'mgmt', evidence: 'Managed 80+ people across squads — Dexco and Vivadecora in parallel.' },
        { id: 'strategy', name: 'Digital Strategy', tree: 'biz', evidence: 'Owned the digital technology strategy at Dexco.' },
        { id: 'perf', name: 'Performance Optimization', tree: 'dev', evidence: '−50% database query time — directly lowering compute cost.' },
        { id: 'nlp', name: 'AI / NLP Chatbots', tree: 'dev', evidence: 'Sales & HR chatbot in Python/NLP on Microsoft Teams.' },
      ],
      boss: {
        name: 'THE 30-SECOND QUERY',
        intro: 'Its health bar is the query time. Every second costs compute money and user patience.',
        question: 'A core query takes 30 seconds and cloud costs climb. First lever?',
        options: [
          'Buy a bigger server',
          'Measure, optimize the queries and the data model',
          'Cache everything and hope',
        ],
        correct: 1,
        hint: 'Hardware hides problems. Optimization removes them.',
        result: '−50% query time at Dexco — faster systems, lower compute cost.',
      },
      badge: {
        id: 'ai',
        icon: '🤖',
        name: 'AI Engineer',
        desc: 'NLP chatbots and applied AI in production — before the hype, kept after it.',
      },
    },
    {
      id: 'ems',
      year: '2024',
      company: 'Scheer Tecnologia · EMS',
      role: 'Founder · Solutions Architect (via Levva)',
      miniCv: [
        'Founded Scheer Tecnologia — consultancy for dedicated teams and solution architecture.',
        'End-to-end ERP integration and modular architecture at EMS (pharma).',
        'Generative AI automation, decision-support analytics, NLP chatbot; zero-downtime data migration.',
      ],
      skills: [
        { id: 'founder', name: 'Company Founding', tree: 'biz', evidence: 'Scheer Tecnologia LTDA — own consultancy, enterprise clients.' },
        { id: 'genai', name: 'Generative AI', tree: 'dev', evidence: 'Process automation with GenAI and an NLP chatbot on Teams (FastAPI, TensorFlow).' },
        { id: 'migration', name: 'Zero-Downtime Migration', tree: 'dev', evidence: 'Secure data migration at EMS with zero service disruption.' },
      ],
      boss: {
        name: 'THE UNTOUCHABLE LEGACY',
        intro: 'A pharma ERP that cannot blink. The data must move — compliance is watching.',
        question: 'Migrate critical data with zero downtime. Strategy?',
        options: [
          'Big-bang cutover on a Friday night',
          'Phased migration with validation, rollback plan and zero disruption',
          'Copy the database and hope for the best',
        ],
        correct: 1,
        hint: 'In pharma, "hope" is not a rollback plan.',
        result: 'Zero-downtime migration delivered at EMS — integrity, security, compliance.',
      },
      badge: {
        id: 'founder',
        icon: '🏢',
        name: 'Founder',
        desc: 'Founded Scheer Tecnologia LTDA (2024) — delivering teams and architecture to enterprises.',
      },
    },
    {
      id: 'crefisa',
      year: '2024–2025',
      company: 'Scheer · Crefisa',
      role: 'Solution Architect (via Avanade · Accenture)',
      miniCv: [
        'Reusable solution-architecture templates: APIs, BFF, EDA, .NET, Python, data pipelines.',
        'Core components: Kafka/IBM MQ, resilient HTTP clients, Redis caching, JWT auth.',
        'Led Architecture Review Boards; DevOps/CI-CD governance for financial systems.',
      ],
      skills: [
        { id: 'eda', name: 'EDA & Kafka', tree: 'dev', evidence: 'Event-driven components with Kafka and IBM MQ for financial systems.' },
        { id: 'archgov', name: 'Architecture Governance', tree: 'mgmt', evidence: 'Architecture Review Boards, guidelines and DevOps/CI-CD governance.' },
        { id: 'templates', name: 'Architecture Templates', tree: 'biz', evidence: 'Reusable templates that cut delivery time and infrastructure cost across teams.' },
      ],
      boss: {
        name: 'THE REVIEW BOARD',
        intro: 'Five architects, one question, all eyes on you: defend your design.',
        question: 'The board asks: why Kafka and not simple HTTP calls?',
        options: [
          'Because everyone uses Kafka',
          'Show the trade-offs: decoupling, resilience and replay vs operational cost',
          'Refuse to answer — the design speaks for itself',
        ],
        correct: 1,
        hint: 'Architecture is decided with trade-offs, not fashion.',
        result: 'Templates approved: less delivery time, less infra cost, across every team.',
      },
      badge: {
        id: 'learner',
        icon: '📜',
        name: 'Lifelong Learner',
        desc: '18+ certifications: Google GenAI, Product School (Strategy, Roadmapping, Analytics, Launches), Databricks (ETL, MLflow, Delta Lake), Six Sigma, Scrum, IDEO Design Thinking.',
      },
    },
    {
      id: 'r10',
      year: '2025–present',
      company: 'Scheer · R10 (Grupo OTG)',
      role: 'Engineering & Architecture Lead',
      miniCv: [
        'Real-time sports data platform: web, mobile and live services, plus analytics products.',
        'Real-time backbone: Python/FastAPI hub, gRPC/Protobuf dataloader, Redis pub/sub, Go WebSocket fan-out.',
        'Scaled 10x — 100K to 1M+ concurrent users at sub-300ms P99 — with ~57% lower operating cost.',
      ],
      skills: [
        { id: 'realtime', name: 'Real-Time Systems', tree: 'dev', evidence: 'WebSockets, gRPC/Protobuf and pub/sub serving live sports data.' },
        { id: 'go', name: 'Go at Scale', tree: 'dev', evidence: 'Go fan-out and push services holding 1M+ concurrent connections.' },
        { id: 'finops', name: 'FinOps', tree: 'biz', evidence: '~57% lower operating cost (≈2.3x cheaper) while scaling 10x.' },
      ],
      boss: {
        name: 'ONE MILLION CONCURRENT',
        intro: 'The final boss. 100K users today, 1M+ tomorrow — and the budget must go DOWN, not up.',
        question: 'Scale 10x and cut cost at the same time. What is the play?',
        options: [
          'Scale vertically and pay whatever the bill says',
          'Redesign the backbone: gRPC + pub/sub + Go fan-out, measure everything',
          'Cap the number of users',
        ],
        correct: 1,
        hint: 'This one needs all three trees: architecture, leadership and FinOps.',
        result: '10x scale: 100K → 1M+ concurrent users, P99 < 300ms, ~57% lower operating cost.',
      },
      badge: {
        id: 'million',
        icon: '⚡',
        name: '1M Concurrent',
        desc: '100K → 1M+ concurrent users, sub-300ms P99, ≈57% lower operating cost.',
      },
    },
    {
      id: 'epilogue',
      year: '2026–?',
      company: 'Your company?',
      role: 'Engineering Manager · Head of Technology · Solutions Architect',
      miniCv: [
        'Open to remote opportunities in engineering/technology leadership.',
        '20+ years in technology, 10+ leading teams; squads of 80+ people, R$26M+ portfolio.',
        'English (full professional) · Portuguese (native) · German (intermediate).',
      ],
      skills: [],
    },
  ],
};
