import type { GameDictionary } from './types';

export const gamePt: GameDictionary = {
  meta: {
    title: 'Career Quest — Jogue os 20 anos de jornada do Philip Scheer em tecnologia',
    description:
      'Um currículo jogável: percorra 20+ anos de liderança em tecnologia, desbloqueie habilidades de desenvolvimento, gestão e negócio e vença chefes reais — do primeiro Hello World a 1M+ de usuários simultâneos.',
  },
  page: {
    title: 'Career Quest',
    intro:
      'Me conheça jogando. Ande para frente (e para trás) por 20+ anos de tecnologia: colete habilidades, ganhe insígnias e vença os desafios reais que enfrentei — o chefe final é um milhão de usuários simultâneos.',
    noscript:
      'O Career Quest precisa de JavaScript. Prefere o caminho clássico? Veja a página de Experiência ou baixe o currículo.',
  },
  ui: {
    startTitle: 'CAREER QUEST',
    tagline: '20+ anos transformando ideias em produtos de baixo custo e alta performance. Jogue a jornada.',
    howTitle: 'Como jogar',
    how: [
      '← → ou A/D — ande no tempo, para frente e para trás',
      'Espaço ou ↑ — pular',
      'E ou toque no aviso — enfrentar o chefe',
      'Encoste nas gemas flutuantes para coletar habilidades (Desenvolvimento · Gestão · Negócio)',
      'Vença o chefe de cada era para liberar o próximo capítulo',
    ],
    recruiterNote:
      'Recrutador com pressa? Abra o mapa da linha do tempo: viaje direto para qualquer fase — cada uma é um mini-currículo.',
    startBtn: 'Press Start (2005)',
    openMapBtn: 'Abrir mapa da linha do tempo',
    hudXp: 'XP',
    hudSkills: 'Skills',
    hudMap: 'Mapa',
    hudCv: 'Mini-CV',
    bossPrompt: 'Aperte E · Enfrentar',
    skillUnlocked: 'Habilidade desbloqueada',
    badgeEarned: 'Insígnia conquistada',
    bossChallenge: 'Desafio do chefe',
    wrongTitle: 'Não foi dessa vez',
    tryAgain: 'Tentar de novo',
    victoryTitle: 'Desafio superado',
    continueBtn: 'Continuar',
    closeBtn: 'Fechar',
    mapTitle: 'Linha do tempo da carreira',
    mapHint: 'Clique em uma fase para viajar até ela. Este mapa é o currículo inteiro de relance.',
    travelBtn: 'Viajar',
    cvTitle: 'Mini-CV',
    trees: { dev: 'Desenvolvimento', mgmt: 'Gestão', biz: 'Negócio' },
    touchLeft: 'Andar para a esquerda',
    touchRight: 'Andar para a direita',
    touchJump: 'Pular',
    touchAction: 'Interagir',
  },
  final: {
    title: 'Próxima fase: a sua empresa?',
    body:
      'Você acabou de percorrer 20+ anos — da sala de aula do colégio técnico a uma plataforma em tempo real servindo 1M+ de usuários simultâneos com 57% menos custo. As habilidades são reais, as métricas são reais, e a próxima batalha pode ser a sua.',
    statsXp: 'XP acumulado',
    statsSkills: 'Habilidades coletadas',
    statsBadges: 'Insígnias conquistadas',
    ctaContact: 'Fale comigo',
    ctaResume: 'Baixar currículo',
    ctaLinkedin: 'Conectar no LinkedIn',
    replay: 'Jogar de novo',
  },
  zones: [
    {
      id: 'school',
      year: '2005–2007',
      company: 'Clovis Bevilacqua',
      role: 'Técnico em Informática (Colégio Técnico)',
      miniCv: [
        'Formação técnica em Tecnologia da Informação.',
        'Primeiro contato com lógica de programação e orientação a objetos.',
        'Onde toda a jornada começa — fase tutorial.',
      ],
      skills: [
        { id: 'logic', name: 'Lógica de Programação', tree: 'dev', evidence: 'Colégio técnico em Informática — Clovis Bevilacqua (2005–2007).' },
        { id: 'oop', name: 'Fundamentos de POO', tree: 'dev', evidence: 'Programação orientada a objetos, a base de tudo que vem depois.' },
      ],
      boss: {
        name: 'A PROVA FINAL',
        intro: 'Uma muralha de questões bloqueia a porta para o mundo real. Quem decorou não passa.',
        question: 'A prova mostra um laço que você nunca viu. O que te faz passar?',
        options: [
          'Decorar o gabarito',
          'Rastrear a lógica passo a passo',
          'Colar do amigo e torcer',
        ],
        correct: 1,
        hint: 'Em tecnologia, entender vence decorar — sempre.',
        result: 'Lógica em primeiro lugar. Técnico concluído — próxima parada: código em produção.',
      },
    },
    {
      id: 'datatex',
      year: '2008–2009',
      company: 'Datatex',
      role: 'Desenvolvedor Web',
      miniCv: [
        'Primeiro emprego como dev: WordPress, PHP, HTML/CSS/JS e projetos Python/Django em vários estágios.',
        'Correção de problemas ao vivo em projetos de clientes.',
        'Início do Bacharelado em Ciência da Computação na FAENAC (2008–2011) em paralelo.',
      ],
      skills: [
        { id: 'web', name: 'PHP & WordPress', tree: 'dev', evidence: 'Sites de clientes e plugins WordPress customizados na Datatex.' },
        { id: 'django', name: 'Python / Django', tree: 'dev', evidence: 'Projetos em Python-Django junto com PHP e JS.' },
      ],
      boss: {
        name: 'O SITE FORA DO AR',
        intro: 'O site do cliente acabou de quebrar. Usuários reais, negócio real, sem ambiente de staging.',
        question: 'O site caiu e a correção precisa ir para o ar agora. Primeiro passo?',
        options: [
          'Reproduzir o bug e ler os logs de erro',
          'Reescrever o site inteiro do zero',
          'Culpar o desenvolvedor anterior',
        ],
        correct: 0,
        hint: 'Você não conserta o que não consegue reproduzir.',
        result: 'Primeira correção em produção entregue. WordPress, PHP ou Django — o que o projeto pedir.',
      },
    },
    {
      id: 'brpart',
      year: '2009–2012',
      company: 'BR part / Synchro',
      role: 'Analista de Sistemas',
      miniCv: [
        'Suporte até 3º nível, instalação e tuning de servidores de aplicação (JBoss, WebSphere).',
        'Aplicações web Java, documentação de projetos e procedimentos de resolução de problemas.',
        'Treinamento e apresentação de ferramentas fiscais brasileiras (NFe / CTe / EMIF).',
      ],
      skills: [
        { id: 'javaee', name: 'Java EE', tree: 'dev', evidence: 'Aplicações Java configuradas, customizadas e publicadas em JBoss/WebSphere.' },
        { id: 'n3', name: 'Suporte N3', tree: 'mgmt', evidence: 'Suporte de 3º nível: a dor do usuário vira o seu roadmap.' },
        { id: 'fiscal', name: 'Compliance Fiscal BR', tree: 'biz', evidence: 'NFe, CTe e EMIF — requisitos fiscais e tributários brasileiros a fundo.' },
      ],
      boss: {
        name: 'O MONSTRO DO COMPLIANCE',
        intro: 'Ele ataca com um novo layout de NFe a cada poucos meses. Todos os clientes precisam continuar em dia.',
        question: 'Um novo layout de NFe chega mês que vem. Como sobreviver às regras fiscais brasileiras?',
        options: [
          'Hardcodar o novo layout o mais rápido possível',
          'Ler a especificação, versionar os layouts, documentar a mudança',
          'Esperar — vai que o governo adia',
        ],
        correct: 1,
        hint: 'Compliance é um alvo em movimento. Versionamento e documentação são a sua armadura.',
        result: 'NFe/CTe domados. Documentação e disciplina de suporte viraram habilidades permanentes.',
      },
      badge: {
        id: 'graduation',
        icon: '🎓',
        name: 'Graduação',
        desc: 'Bacharelado em Ciência da Computação — Universidade FAENAC, São Paulo (2008–2011).',
      },
    },
    {
      id: 'itc',
      year: '2012–2015',
      company: 'IT Convergence',
      role: 'Consultor de TI',
      miniCv: [
        'Consultoria internacional: suporte até 3º nível para clientes globais.',
        'Instalação e atualização de servidores de aplicação (JBoss, WebSphere, OA).',
        'Documentação, planos de projeto e procedimentos — em inglês.',
      ],
      skills: [
        { id: 'appservers', name: 'App Servers em Escala', tree: 'dev', evidence: 'JBoss, WebSphere e OA instalados, atualizados e vivos para clientes enterprise.' },
        { id: 'english', name: 'Inglês Profissional', tree: 'biz', evidence: 'Contato diário com parceiros e clientes internacionais.' },
      ],
      boss: {
        name: 'O SERVIDOR CAÍDO ÀS 3H',
        intro: 'Produção fora do ar, o relógio marca 3h07, e o cliente na call só fala inglês.',
        question: 'E agora?',
        options: [
          'Esperar o turno da manhã',
          'Entrar na call, comunicar o status com clareza, restaurar o serviço, escrever o postmortem',
          'Reiniciar tudo e não falar nada',
        ],
        correct: 1,
        hint: 'Incidentes se vencem com comunicação + procedimento, não com silêncio.',
        result: 'Incidente encerrado. Clientes internacionais, inglês sob pressão, procedimentos documentados.',
      },
      badge: {
        id: 'english',
        icon: '🌐',
        name: 'English Unlocked',
        desc: 'Inglês profissional pleno — a chave que abriu o mercado internacional.',
      },
    },
    {
      id: 'synchro',
      year: '2015–2017',
      company: 'Synchro',
      role: 'Desenvolvedor J2EE Sênior',
      miniCv: [
        'Integrações com Oracle E-Business Suite (AR/RI) e Oracle Retail usando ODI e BPEL.',
        'Integrações com SAP Business One; PL/SQL, Java EE, VB6, ABAP e HANA.',
        'Domínio profundo dos requisitos fiscais brasileiros em toda a suíte de solução fiscal.',
      ],
      skills: [
        { id: 'oracle', name: 'Oracle PL/SQL & HANA', tree: 'dev', evidence: 'PL/SQL, ODI, BPEL e HANA em sistemas fiscais enterprise.' },
        { id: 'erp', name: 'Integrações ERP', tree: 'dev', evidence: 'Oracle EBS e SAP B1 conversando sem quebrar o fechamento do mês.' },
      ],
      boss: {
        name: 'AS DUAS GIGANTES',
        intro: 'Oracle EBS de um lado. SAP do outro. Os dados precisam fluir nos dois sentidos — o fechamento não pode quebrar.',
        question: 'Como fazer duas gigantes de ERP cooperarem?',
        options: [
          'Scripts ponto a ponto para todo lado',
          'Uma camada de integração (ODI/BPEL) com contratos, versionamento e monitoramento',
          'Planilhas manuais toda semana',
        ],
        correct: 1,
        hint: 'Gigantes precisam de diplomatas: contratos e uma camada de integração de verdade.',
        result: 'Integrações de nível sênior entregues: Oracle ⇄ SAP com ODI, BPEL, PL/SQL e HANA.',
      },
    },
    {
      id: 'didi',
      year: '2017–2019',
      company: '99 (empresa DiDi)',
      role: 'Principal Software Engineer — Pagamentos & Arquitetura',
      miniCv: [
        'Autor da Arquitetura Global de Aplicações entre Brasil, EUA e China.',
        'Integrações de ERP SAP B1 (B1if, DI API, Add-ons) para mercados globais.',
        'Coordenação de 18 projetos simultâneos e contratos de terceiros; compliance fiscal profundo.',
      ],
      skills: [
        { id: 'globalarch', name: 'Arquitetura Global', tree: 'dev', evidence: 'Autor da Arquitetura Global de Aplicações na 99 (DiDi).' },
        { id: 'payments', name: 'Pagamentos & Fintech', tree: 'biz', evidence: 'Domínio de pagamentos e compliance fiscal/tributário brasileiro em escala.' },
        { id: 'portfolio', name: 'Gestão de Portfólio', tree: 'mgmt', evidence: '18 projetos simultâneos entregues no prazo, com contratos de terceiros.' },
      ],
      boss: {
        name: 'A HIDRA DOS 18 PROJETOS',
        intro: 'Dezoito cabeças, três países, um prazo para cada uma. Corte a errada e nascem duas.',
        question: '18 projetos simultâneos entre Brasil, EUA e China. Como manter as cabeças abaixadas?',
        options: [
          'Fazer tudo sozinho, dormir depois',
          'Priorizar por impacto, padronizar a arquitetura, delegar e acompanhar',
          'Congelar todos os projetos até segunda ordem',
        ],
        correct: 1,
        hint: 'Um Principal Engineer escala por arquitetura e prioridade, não por horas.',
        result: '18 projetos entregues no prazo — os dados de fechamento financeiro nunca atrasaram.',
      },
      badge: {
        id: 'globetrotter',
        icon: '✈️',
        name: 'Globetrotter',
        desc: 'Viagens de trabalho: Nova York, Califórnia — Palo Alto / Vale do Silício — e Beijing, além de São Paulo, Rio, Belo Horizonte, Curitiba, Campinas, Cuiabá e Maringá pelo Brasil.',
      },
    },
    {
      id: 'restoque',
      year: '2019–2020',
      company: 'Restoque S/A',
      role: 'Gerente de Tecnologia e Inovação',
      miniCv: [
        'Liderança de 3 times — Produto, Inovação e UX Labs — 27 pessoas no total.',
        'Visão de produto e roadmaps a partir de pesquisa de mercado, concorrência e clientes.',
        'Design Sprints, redesign de app em Flutter, CI/CD (Rancher, Azure, GCP) e um SaaS para apps de alta demanda.',
      ],
      skills: [
        { id: 'leadership', name: 'Liderança de Times', tree: 'mgmt', evidence: '3 times, 27 pessoas: a troca de escrever código por desenvolver pessoas.' },
        { id: 'roadmap', name: 'Roadmaps & Design Sprints', tree: 'mgmt', evidence: 'Visão de produto construída com pesquisa, entregue em cadências Scrum.' },
        { id: 'flutter', name: 'Flutter & CI/CD', tree: 'dev', evidence: 'Redesign de app em Flutter com CI/CD em Rancher, Azure e GCP.' },
      ],
      boss: {
        name: 'A TROCA DE CHAPÉU',
        intro: 'Um bug crítico aparece. O antigo você viraria a noite codando. Mas 27 pessoas estão olhando o que você faz agora.',
        question: 'Agora você é o gestor. O que o líder faz?',
        options: [
          'Codar sozinho a noite toda — velhos hábitos',
          'Colocar as pessoas certas no problema, desbloquear o time, proteger o roadmap',
          'Escalar direto para o CEO',
        ],
        correct: 1,
        hint: 'A habilidade mais difícil para um ótimo engenheiro: vencer através do time.',
        result: 'Primeiro capítulo de liderança: 3 times, 27 pessoas, roadmaps e cultura de entrega.',
      },
      badge: {
        id: 'firstlead',
        icon: '👑',
        name: 'Primeira Liderança',
        desc: 'De engenheiro sênior a líder de 27 pessoas em Produto, Inovação e UX Labs.',
      },
    },
    {
      id: 'dell',
      year: '2020–2022',
      company: 'Dell Technologies',
      role: 'Design System Manager (Remoto, EUA & Brasil)',
      miniCv: [
        'Construção e governança de um design system corporativo: padrões, documentação, ferramentas.',
        'Visão e roadmap a partir de tendências de mercado, em parceria com líderes de design e engenharia.',
        'Entrega incremental e ágil de componentes — 100% remoto entre times EUA/Brasil.',
      ],
      skills: [
        { id: 'designsystem', name: 'Design Systems', tree: 'dev', evidence: 'Design system corporativo governado na Dell Technologies.' },
        { id: 'governance', name: 'Governança', tree: 'mgmt', evidence: 'Padrões, documentação e ferramentas que escalam além de um time.' },
        { id: 'remote', name: 'Trabalho Remoto Internacional', tree: 'mgmt', evidence: '100% remoto entre times e fusos EUA/Brasil.' },
      ],
      boss: {
        name: 'O CAOS DA INCONSISTÊNCIA',
        intro: 'O mesmo botão aparece com 12 visuais diferentes entre os produtos. Os usuários percebem. A marca sofre.',
        question: 'Como derrotar o caos em escala enterprise?',
        options: [
          'Deixar cada time com o próprio estilo',
          'Um design system governado: padrões, docs, ferramentas, adoção incremental',
          'Um redesign big-bang — congelar todo o produto',
        ],
        correct: 1,
        hint: 'Consistência é um sistema, não um redesign heroico.',
        result: 'Design system corporativo entregue: reúso mais rápido, menor custo de build, uma só marca.',
      },
      badge: {
        id: 'remotemaster',
        icon: '🏠',
        name: 'Mestre do Remoto',
        desc: 'Dois anos liderando 100% remoto entre EUA/Brasil — antes de ser normal.',
      },
    },
    {
      id: 'dexco',
      year: '2022–2024',
      company: 'Dexco (Duratex) · Vivadecora',
      role: 'Gerente Sênior de Tecnologia',
      miniCv: [
        'Liderança da estratégia de tecnologia digital ponta a ponta, sistemas e infraestrutura de TI.',
        'Gestão de 80+ pessoas em squads, conduzindo Dexco e Vivadecora em paralelo.',
        'Redução de 50% no tempo de query do banco com otimização avançada.',
        'Chatbot de IA para Vendas e RH (Python, NLP) integrado ao Microsoft Teams.',
      ],
      skills: [
        { id: 'squads', name: 'Escala de Squads (80+)', tree: 'mgmt', evidence: 'Gestão de 80+ pessoas em squads — Dexco e Vivadecora em paralelo.' },
        { id: 'strategy', name: 'Estratégia Digital', tree: 'biz', evidence: 'Dono da estratégia de tecnologia digital na Dexco.' },
        { id: 'perf', name: 'Otimização de Performance', tree: 'dev', evidence: '−50% no tempo de query — reduzindo diretamente o custo de processamento.' },
        { id: 'nlp', name: 'IA / Chatbots NLP', tree: 'dev', evidence: 'Chatbot de Vendas & RH em Python/NLP no Microsoft Teams.' },
      ],
      boss: {
        name: 'A QUERY DE 30 SEGUNDOS',
        intro: 'A barra de vida dele é o tempo da query. Cada segundo custa dinheiro de computação e paciência do usuário.',
        question: 'Uma query central leva 30 segundos e o custo de cloud sobe. Primeira alavanca?',
        options: [
          'Comprar um servidor maior',
          'Medir, otimizar as queries e o modelo de dados',
          'Cachear tudo e torcer',
        ],
        correct: 1,
        hint: 'Hardware esconde problemas. Otimização remove.',
        result: '−50% no tempo de query na Dexco — sistemas mais rápidos, menos custo de computação.',
      },
      badge: {
        id: 'ai',
        icon: '🤖',
        name: 'Engenheiro de IA',
        desc: 'Chatbots NLP e IA aplicada em produção — antes do hype, mantido depois dele.',
      },
    },
    {
      id: 'ems',
      year: '2024',
      company: 'Scheer Tecnologia · EMS',
      role: 'Fundador · Arquiteto de Soluções (via Levva)',
      miniCv: [
        'Fundação da Scheer Tecnologia — consultoria de times dedicados e arquitetura de soluções.',
        'Integração de ERP ponta a ponta e arquitetura modular na EMS (farmacêutica).',
        'Automação com IA generativa, analytics de apoio à decisão, chatbot NLP; migração de dados sem downtime.',
      ],
      skills: [
        { id: 'founder', name: 'Fundação de Empresa', tree: 'biz', evidence: 'Scheer Tecnologia LTDA — consultoria própria, clientes enterprise.' },
        { id: 'genai', name: 'IA Generativa', tree: 'dev', evidence: 'Automação de processos com GenAI e chatbot NLP no Teams (FastAPI, TensorFlow).' },
        { id: 'migration', name: 'Migração Zero-Downtime', tree: 'dev', evidence: 'Migração de dados segura na EMS com zero interrupção de serviço.' },
      ],
      boss: {
        name: 'O LEGADO INTOCÁVEL',
        intro: 'Um ERP farmacêutico que não pode piscar. Os dados precisam se mover — o compliance está de olho.',
        question: 'Migrar dados críticos com zero downtime. Estratégia?',
        options: [
          'Virada big-bang numa sexta à noite',
          'Migração em fases com validação, plano de rollback e zero interrupção',
          'Copiar o banco e torcer',
        ],
        correct: 1,
        hint: 'Na indústria farmacêutica, "torcer" não é plano de rollback.',
        result: 'Migração sem downtime entregue na EMS — integridade, segurança, compliance.',
      },
      badge: {
        id: 'founder',
        icon: '🏢',
        name: 'Fundador',
        desc: 'Fundou a Scheer Tecnologia LTDA (2024) — entregando times e arquitetura para empresas.',
      },
    },
    {
      id: 'crefisa',
      year: '2024–2025',
      company: 'Scheer · Crefisa',
      role: 'Arquiteto de Soluções (via Avanade · Accenture)',
      miniCv: [
        'Templates reutilizáveis de arquitetura: APIs, BFF, EDA, .NET, Python, pipelines de dados.',
        'Componentes core: Kafka/IBM MQ, clients HTTP resilientes, cache Redis, autenticação JWT.',
        'Condução de Architecture Review Boards; governança de DevOps/CI-CD para sistemas financeiros.',
      ],
      skills: [
        { id: 'eda', name: 'EDA & Kafka', tree: 'dev', evidence: 'Componentes orientados a eventos com Kafka e IBM MQ para sistemas financeiros.' },
        { id: 'archgov', name: 'Governança de Arquitetura', tree: 'mgmt', evidence: 'Architecture Review Boards, diretrizes e governança de DevOps/CI-CD.' },
        { id: 'templates', name: 'Templates de Arquitetura', tree: 'biz', evidence: 'Templates reutilizáveis que reduziram tempo de entrega e custo de infra entre times.' },
      ],
      boss: {
        name: 'O CONSELHO DE ARQUITETURA',
        intro: 'Cinco arquitetos, uma pergunta, todos os olhos em você: defenda o seu design.',
        question: 'O conselho pergunta: por que Kafka e não chamadas HTTP simples?',
        options: [
          'Porque todo mundo usa Kafka',
          'Mostrar os trade-offs: desacoplamento, resiliência e replay vs custo operacional',
          'Recusar a resposta — o design fala por si',
        ],
        correct: 1,
        hint: 'Arquitetura se decide com trade-offs, não com moda.',
        result: 'Templates aprovados: menos tempo de entrega, menos custo de infra, em todos os times.',
      },
      badge: {
        id: 'learner',
        icon: '📜',
        name: 'Aprendiz Eterno',
        desc: '18+ certificações: Google GenAI, Product School (Strategy, Roadmapping, Analytics, Launches), Databricks (ETL, MLflow, Delta Lake), Six Sigma, Scrum, IDEO Design Thinking.',
      },
    },
    {
      id: 'r10',
      year: '2025–atual',
      company: 'Scheer · R10 (Grupo OTG)',
      role: 'Líder de Engenharia & Arquitetura',
      miniCv: [
        'Plataforma de dados esportivos em tempo real: web, mobile e serviços ao vivo, além de produtos de analytics.',
        'Backbone em tempo real: hub Python/FastAPI, dataloader gRPC/Protobuf, Redis pub/sub, fan-out WebSocket em Go.',
        'Escala 10x — de 100K para 1M+ usuários simultâneos com P99 < 300ms — e ~57% menos custo de operação.',
      ],
      skills: [
        { id: 'realtime', name: 'Sistemas em Tempo Real', tree: 'dev', evidence: 'WebSockets, gRPC/Protobuf e pub/sub servindo dados esportivos ao vivo.' },
        { id: 'go', name: 'Go em Escala', tree: 'dev', evidence: 'Serviços de fan-out e push em Go segurando 1M+ de conexões simultâneas.' },
        { id: 'finops', name: 'FinOps', tree: 'biz', evidence: '~57% menos custo de operação (≈2,3x mais barato) escalando 10x.' },
      ],
      boss: {
        name: 'UM MILHÃO SIMULTÂNEOS',
        intro: 'O chefe final. 100K usuários hoje, 1M+ amanhã — e o orçamento precisa DESCER, não subir.',
        question: 'Escalar 10x e cortar custo ao mesmo tempo. Qual é a jogada?',
        options: [
          'Escalar verticalmente e pagar a conta que vier',
          'Redesenhar o backbone: gRPC + pub/sub + fan-out em Go, medindo tudo',
          'Limitar o número de usuários',
        ],
        correct: 1,
        hint: 'Este precisa das três árvores: arquitetura, liderança e FinOps.',
        result: 'Escala 10x: 100K → 1M+ usuários simultâneos, P99 < 300ms, ~57% menos custo de operação.',
      },
      badge: {
        id: 'million',
        icon: '⚡',
        name: '1M Simultâneos',
        desc: '100K → 1M+ usuários simultâneos, P99 abaixo de 300ms, ≈57% menos custo de operação.',
      },
    },
    {
      id: 'epilogue',
      year: '2026–?',
      company: 'A sua empresa?',
      role: 'Engineering Manager · Head of Technology · Arquiteto de Soluções',
      miniCv: [
        'Aberto a oportunidades remotas em liderança de engenharia/tecnologia.',
        '20+ anos em tecnologia, 10+ liderando times; squads de 80+ pessoas, portfólio de R$26M+.',
        'Inglês (profissional pleno) · Português (nativo) · Alemão (intermediário).',
      ],
      skills: [],
    },
  ],
};
